version: '3.8'

services:
  nv_freemold:
    image: consol/debian-xfce-vnc:v2.0.3
    container_name: nv_test
    ports:
      - "9608:6901"  # 映射 noVNC 端口
      - "9609:5901"  # 映射 VNC 端口（如果需要直接通过 VNC 客户端连接）
    environment:
      - TZ=Asia/Seoul
      - VNC_RESOLUTION=1280x720
      - VNC_PW=1234
      - VNC_COL_DEPTH=24  # 根据 Dockerfile 设置颜色深度
      - VNC_VIEW_ONLY=false  # 根据 Dockerfile 设置是否只读
    volumes:
      - .:/headless/Desktop/data  # 挂载当前目录到容器内的 /headless/Desktop/data
      - ./start.sh:/start.sh  # 挂载自定义启动脚本
    user: "0"  # 根据 Dockerfile 使用非 root 用户运行
    entrypoint: /start.sh